### ISSUE TITLE
Support Web Forms

### ISSUE THREAD

**Issue by cgatian** [gfawcett22/EnterprisePlanner#6]
We need this support for stability

**Comment by zbream** [comment]
+1. I'll put together a PR, send it your way. This is the one thing stopping me from adopting.

**Comment by gfawcett22** [comment]
@zbream  We've got customers migrating from classic ASP to Web Forms so this would be extremely helpful. Also make sure Edge support is there too.

**Comment by cgatian** [comment]
Why was this closed? We need this.
